name: hf_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch-cuda
  - torchvision
  - transformers
  - evaluate
  - accelerate
  - numpy
  - pandas
  - tqdm
  - pip
  - pip:
    - rouge_score